import type { Metadata } from 'next';
import { Twinkle_Star } from 'next/font/google';
import '@/app/layout.scss';
import { ReactNode } from 'react';
import Providers from '@/shared/providers/providers';
import Header from '@/widgets/header/Header';
import Footer from '@/widgets/footer/Footer';

const TwinkleSans = Twinkle_Star({
  variable: '--font-twinkle',
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang={'ru'}>
      <body className={`${TwinkleSans.variable}`}>
        <Providers>
          <Header />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
